name:                sin-hasktorch
version:             0.1.0.0
github:              "githubuser/sin-hasktorch"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sin-hasktorch#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- hasktorch-tools
- gnuplot
- process

# ghc-options:
# - -Wall
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src

executables:
  TypedSinRNN:
    main:                SinRNN.hs
    other-modules:       []
    source-dirs:         app/Typed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is SinRNN
    dependencies:
    - sin-hasktorch

  TypedSinMLP:
    main:                SinMLP.hs
    other-modules:       []
    source-dirs:         app/Typed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is SinMLP  
    dependencies:
    - sin-hasktorch

  inRNN:
    main:                SinRNN.hs
    other-modules:       []
    source-dirs:         app/UnTyped
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is SinRNN
    dependencies:
    - sin-hasktorch

tests:
  sin-hasktorch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sin-hasktorch
