resolver: nightly-2022-10-11

extra-include-dirs:
  - ../../.pyenv/versions/miniconda-3.9.1/envs/pytorch/include
  - ../../.local/lib/hasktorch/deps/libtorch/include/torch/csrc/api/include
  - ../../.local/lib/hasktorch/deps/libtorch/include

extra-lib-dirs:
  - ../../.local/lib/hasktorch/deps/libtorch/lib
  - ../../.pyenv/versions/miniconda-3.9.1/envs/pytorch/lib
  - ../../.local/lib/hasktorch/deps/libtokenizers/lib

extra-deps:
  - git: https://github.com/DaisukeBekki/nlp-tools.git
    commit: 0b6912850dbffd14ed16c3fa26a0773c877ba093
  - /home/acc12242uy/.local/lib/hasktorch/codegen
  - /home/acc12242uy/.local/lib/hasktorch/libtorch-ffi
  - /home/acc12242uy/.local/lib/hasktorch/libtorch-ffi-helper
  - /home/acc12242uy/.local/lib/hasktorch/hasktorch
  - /home/acc12242uy/.local/lib/hasktorch-tools
  - git: https://github.com/fpco/inline-c
    commit: 2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0
    subdirs:
    - inline-c
  - git: https://github.com/fpco/inline-c
    commit: 2d0fe9b2f0aa0e1aefc7bfed95a501e59486afb0
    subdirs:
    - inline-c-cpp

allow-newer: true
